"use client";

import Link from "next/link";
import { ChangeEvent, useCallback, useEffect, useRef, useState } from "react";

type Asset={id:string;name:string;kind:string;role:string;mimeType:string|null;bytes:number;media:Record<string,unknown>;checksum:{value:string};extensions:{archived?:boolean}};
type ActionDocument<T>={result:T};
type Reservation={upload:{path:string};complete:{input:{transferToken:string}}};

function transferPath(path:string){return path.replace("/api/v1/assets/transfers/","/api/studio/assets/transfers/");}
function fileKind(file:File){if(file.type.startsWith("video/"))return "video";if(file.type.startsWith("audio/"))return "audio";if(file.type.startsWith("image/"))return "image";return null;}
function sizeLabel(bytes:number){if(bytes<1024*1024)return `${Math.max(1,Math.round(bytes/1024))} KB`;return `${(bytes/1024/1024).toFixed(1)} MB`;}

export function HostedAssetLibrary({projectId}:{projectId:string}){
  const [assets,setAssets]=useState<Asset[]>([]);const [previews,setPreviews]=useState<Record<string,string>>({});const [active,setActive]=useState<Asset|null>(null);
  const [file,setFile]=useState<File|null>(null);const [progress,setProgress]=useState(0);const [status,setStatus]=useState<"idle"|"uploading"|"failed">("idle");const [message,setMessage]=useState("Upload a video, audio, or image source. Originals remain private and tenant-owned.");const xhr=useRef<XMLHttpRequest|null>(null);
  const call=useCallback(async<T,>(actionId:string,input:Record<string,unknown>,approved=false):Promise<T>=>{const response=await fetch(`/api/studio/actions/${actionId}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({input,approved})});const payload=await response.json();if(!response.ok)throw new Error(payload.detail?.message||payload.detail||payload.message||`Action failed (${response.status}).`);return (payload as ActionDocument<T>).result;},[]);
  const load=useCallback(async()=>{try{const rows=await call<Asset[]>("asset.list",{projectId});setAssets(rows);setActive(current=>current&&rows.some(row=>row.id===current.id)?current:null);const urls=await Promise.all(rows.map(async row=>{try{const value=await call<{path:string}>("asset.download.request",{projectId,assetId:row.id});return [row.id,transferPath(value.path)] as const;}catch{return [row.id,""] as const;}}));setPreviews(Object.fromEntries(urls));}catch(reason){setMessage(reason instanceof Error?reason.message:"Asset library could not be loaded.");}},[call,projectId]);
  useEffect(()=>{void load();},[load]);
  function choose(event:ChangeEvent<HTMLInputElement>){const selected=event.target.files?.[0]||null;if(!selected)return;const kind=fileKind(selected);if(!kind){setFile(null);setStatus("failed");setMessage("Choose a supported video, audio, or image file.");return;}setFile(selected);setStatus("idle");setProgress(0);setMessage(`${selected.name} is ready to upload.`);}
  async function upload(){if(!file)return;const kind=fileKind(file);if(!kind)return;setStatus("uploading");setProgress(0);setMessage("Reserving tenant-owned storage…");try{const reservation=await call<Reservation>("asset.upload.request",{projectId,filename:file.name,kind,role:"source",mimeType:file.type,bytes:file.size,sourceType:"upload"});await new Promise<void>((resolve,reject)=>{const request=new XMLHttpRequest();xhr.current=request;request.open("PUT",transferPath(reservation.upload.path));request.setRequestHeader("content-type",file.type);request.upload.onprogress=event=>{if(event.lengthComputable)setProgress(Math.round(event.loaded/event.total*100));};request.onload=()=>request.status>=200&&request.status<300?resolve():reject(new Error(`Upload failed (${request.status}).`));request.onerror=()=>reject(new Error("Upload connection failed."));request.onabort=()=>reject(new Error("Upload cancelled. You can retry the same file."));request.send(file);});setMessage("Verifying checksum and recording provenance…");const asset=await call<Asset>("asset.upload.complete",{projectId,transferToken:reservation.complete.input.transferToken});setActive(asset);setFile(null);setStatus("idle");setProgress(100);setMessage(`${asset.name} is stored and ready. A duplicate checksum reuses the existing asset.`);await load();}catch(reason){setStatus("failed");setMessage(reason instanceof Error?reason.message:"Upload failed. Retry the same file.");}finally{xhr.current=null;}}
  function cancel(){xhr.current?.abort();}
  async function archive(asset:Asset){try{await call("asset.archive",{projectId,assetId:asset.id},true);setMessage(`${asset.name} was archived. Its original bytes and edit history were retained safely.`);await load();}catch(reason){setMessage(reason instanceof Error?reason.message:"Asset could not be archived.");}}
  async function use(asset:Asset){try{await call("asset.timeline.add",{projectId,assetId:asset.id});setMessage(`${asset.name} is now on the project timeline.`);}catch(reason){setMessage(reason instanceof Error?reason.message:"Asset could not be added to the timeline.");}}
  const activeUrl=active?previews[active.id]:null;
  return <div className="footage-workbench hosted-assets">
    <header className="studio-head studio-head-product"><div><div className="eyebrow">Hosted asset library</div><h1>Bring the source. Keep the proof.</h1><p className="muted">Stream real media into tenant-owned storage, then preview it and place it on the canonical project timeline.</p></div><div className="form-actions"><Link className="button secondary" href={`/studio/projects/${encodeURIComponent(projectId)}/edit`}>Timeline</Link><Link className="button secondary" href="/studio">Projects</Link></div></header>
    <div className={`notice ${status==="failed"?"error":""}`} role="status">{message}</div>
    <section className="panel hosted-upload-panel"><div className="panel-head"><div><div className="section-label">01 · Ingest</div><h2>Stream an original.</h2></div><span className="status-pill">video · audio · image</span></div><p className="muted">Uploads stream through the authenticated service instead of buffering the whole file in server memory. Cancel safely or retry the same source after a failure.</p><div className="hosted-upload-row"><label className="button secondary upload-button">Choose media<input accept="video/*,audio/*,image/*" disabled={status==="uploading"} onChange={choose} type="file" /></label><strong>{file?.name||"No file selected"}</strong><span>{file?sizeLabel(file.size):""}</span></div>{file?<div className="upload-progress"><progress max="100" value={progress}/><span>{progress}%</span><button className="button accent" disabled={status==="uploading"} onClick={()=>void upload()} type="button">{status==="failed"?"Retry upload":"Upload source"}</button>{status==="uploading"?<button className="button secondary" onClick={cancel} type="button">Cancel</button>:null}</div>:null}</section>
    <div className="hosted-library-grid"><section className="panel"><div className="panel-head"><div><div className="section-label">02 · Library</div><h2>{assets.length} owned asset{assets.length===1?"":"s"}</h2></div><button className="button secondary" onClick={()=>void load()} type="button">Refresh</button></div>{assets.length?<div className="asset-card-grid">{assets.map(asset=><article className="asset-card" key={asset.id}>{previews[asset.id]&&asset.kind==="image"?<img alt="" src={previews[asset.id]}/>:previews[asset.id]&&asset.kind==="video"?<video aria-label={`${asset.name} thumbnail`} muted preload="metadata" src={`${previews[asset.id]}#t=0.1`}/>:<div className="asset-placeholder">{asset.kind}</div>}<div><strong>{asset.name}</strong><span>{sizeLabel(asset.bytes)} · {asset.mimeType}</span><span>SHA-256 {asset.checksum.value.slice(0,12)}…</span></div><div className="asset-actions"><button onClick={()=>setActive(asset)} type="button">Preview</button><button onClick={()=>void use(asset)} type="button">Use in timeline</button><button onClick={()=>void archive(asset)} type="button">Archive</button></div></article>)}</div>:<div className="preview-empty compact-empty">No media yet. Upload the first original above.</div>}</section><section className="panel hosted-preview"><div className="panel-head"><div><div className="section-label">Preview</div><h2>{active?.name||"Select an asset"}</h2></div></div>{active&&activeUrl?(active.kind==="video"?<video className="footage-preview" controls preload="metadata" src={activeUrl}/>:active.kind==="audio"?<audio controls src={activeUrl}/>:<img alt={active.name} src={activeUrl}/>):<div className="preview-empty">Choose Preview from the library.</div>}</section></div>
  </div>;
}
